// <auto-generated />
using Grade_Manager_Razor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Grade_Manager_Razor.Migrations
{
    [DbContext(typeof(GradeManagerDbContext))]
    [Migration("20211006223706_changedstudentkeys")]
    partial class changedstudentkeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Grade_Manager_Razor.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Grade")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            Grade = 0.0,
                            IsComplete = false,
                            Name = "Lab_1",
                            StudentId = 1
                        },
                        new
                        {
                            AssignmentId = 2,
                            Grade = 0.0,
                            IsComplete = false,
                            Name = "Lab_2",
                            StudentId = 1
                        },
                        new
                        {
                            AssignmentId = 3,
                            Grade = 0.0,
                            IsComplete = false,
                            Name = "Lab_3",
                            StudentId = 1
                        },
                        new
                        {
                            AssignmentId = 4,
                            Grade = 0.0,
                            IsComplete = false,
                            Name = "Lab_4",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Grade_Manager_Razor.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassRoomId");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            ClassRoomId = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ClassRoomId = 2,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("Grade_Manager_Razor.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassRoomId = 1,
                            Name = "JimBob"
                        },
                        new
                        {
                            StudentId = 2,
                            ClassRoomId = 1,
                            Name = "Bradley"
                        },
                        new
                        {
                            StudentId = 3,
                            ClassRoomId = 1,
                            Name = "Steven"
                        },
                        new
                        {
                            StudentId = 4,
                            ClassRoomId = 2,
                            Name = "Jonathon"
                        },
                        new
                        {
                            StudentId = 5,
                            ClassRoomId = 2,
                            Name = "Heather"
                        },
                        new
                        {
                            StudentId = 6,
                            ClassRoomId = 2,
                            Name = "Warren"
                        });
                });

            modelBuilder.Entity("Grade_Manager_Razor.Assignment", b =>
                {
                    b.HasOne("Grade_Manager_Razor.Student", "Student")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Grade_Manager_Razor.Student", b =>
                {
                    b.HasOne("Grade_Manager_Razor.ClassRoom", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Grade_Manager_Razor.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Grade_Manager_Razor.Student", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
